# Generated by Django 4.2.2 on 2023-06-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Номер филиала')),
                ('address', models.CharField(max_length=250, verbose_name='Адрес')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lng', models.FloatField(verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
                'ordering': ['name'],
            },
        ),
    ]
